---
- name: 'Atualizando pacotes'
  yum:
    update_cache: yes

- name: Modificando hostname
  shell: hostname {{ inventory_hostname }}

- name: 'Adicionando repositorio Docker'
  shell: yum-config-manager \ --add-repo \ https://download.docker.com/linux/centos/docker-ce.repo

- name: 'Instalando docker e dependencia'
  yum:
    name:
      - yum-utils
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: 'Adicionando o usuario ao group docker'
  shell: usermod -aG docker $USER